### PR TITLE
Challenge Task [WIP]

### PR DESCRIPTION
**Pull request by svavassori**
This is a PR (still WIP) for localtunnel to support connection on demand to overcome the 10 connection limit

### CODE REVIEW

**Comment by jkuri** [comment]
hi @svavassori. what is the status of this PR?

**Comment by svavassori** [comment]
On 5 March 2018 at 00:58, Jan Kuri <notifications@github.com> wrote:

> hi @svavassori <https://github.com/svavassori>. what is the status of
> this PR?
>

The functionality is there, thus you can use it to evaluate; it could be
that there are minor fixes to do though.

Regards,
Sergio

**Comment by jkuri** [comment]
this doesn't work for me, did you even try to run this?

**Comment by svavassori** [comment]
On 5 March 2018 at 10:12, Jan Kuri <notifications@github.com> wrote:

> this doesn't work for me, did you even try to run this?
>
I didn't run it, it was to give you an idea of how I implemented the
changes at an architectural level.
Did you have any problem compiling it?

**Comment by irmana** [comment]
Not working, thanks for trying it out.

**Pull request closed without merging**
